# Generated by Django 5.1.3 on 2024-11-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MAIN", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="discriotion",
            new_name="discription",
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="MAIN.tag"),
        ),
    ]
